---
monitoring_project_dir: /opt/monitoring

monitoring_loki_version: 3.0.0
monitoring_promtail_version: 3.0.0
monitoring_prometheus_version: v3.9.0
monitoring_grafana_version: 12.3.1

monitoring_prometheus_port: 9090
monitoring_loki_port: 3100
monitoring_promtail_port: 9080
monitoring_grafana_port: 13000
monitoring_python_port: 18000
monitoring_python_internal_port: 5000
monitoring_go_port: 18001
monitoring_go_internal_port: 8080

monitoring_retention_period: 168h
monitoring_schema_version: v13
monitoring_prometheus_retention_time: 15d
monitoring_prometheus_retention_size: 10GB
monitoring_prometheus_scrape_interval: 15s

monitoring_grafana_admin_user: admin
monitoring_grafana_admin_password: ChangeMe123!

monitoring_python_app_image: "{{ dockerhub_username | default('sfedbro') }}/app_python:latest"
monitoring_go_app_image: "{{ dockerhub_username | default('sfedbro') }}/app_go:latest"

monitoring_resources:
  prometheus:
    limits:
      cpus: "1.0"
      memory: 1G
    reservations:
      cpus: "0.25"
      memory: 256M
  loki:
    limits:
      cpus: "1.0"
      memory: 1G
    reservations:
      cpus: "0.25"
      memory: 256M
  promtail:
    limits:
      cpus: "0.50"
      memory: 512M
    reservations:
      cpus: "0.10"
      memory: 128M
  grafana:
    limits:
      cpus: "0.50"
      memory: 512M
    reservations:
      cpus: "0.10"
      memory: 128M
  app_python:
    limits:
      cpus: "0.50"
      memory: 256M
    reservations:
      cpus: "0.10"
      memory: 64M
  app_go:
    limits:
      cpus: "0.50"
      memory: 256M
    reservations:
      cpus: "0.10"
      memory: 64M
