replicaCount: 1
environment: dev
logLevel: debug

featureFlags:
  visitsCounter: true
  configHotReload: true

image:
  tag: lab12
  pullPolicy: Always

service:
  type: NodePort
  nodePort: 30081

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: DEBUG
    value: "true"
  - name: APP_ENV
    value: "dev"
  - name: VISITS_FILE
    value: "/data/visits"
  - name: CONFIG_FILE
    value: "/config/config.json"

configMap:
  env:
    data:
      APP_CONFIG_MODE: configmap
      LOG_LEVEL: debug
      FEATURE_VISITS: "true"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5
