replicaCount: 3

nameOverride: ""
fullnameOverride: ""
environment: dev
logLevel: info

featureFlags:
  visitsCounter: true
  configHotReload: true

image:
  repository: sfedbro/app_python
  tag: lab12
  pullPolicy: Always

containerPort: 5000

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

rollout:
  enabled: false
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
    previewService:
      enabled: true
      type: ClusterIP

statefulset:
  enabled: false
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: DEBUG
    value: "false"
  - name: APP_ENV
    value: "dev"
  - name: VISITS_FILE
    value: "/data/visits"
  - name: CONFIG_FILE
    value: "/config/config.json"

configMap:
  enabled: true
  mountPath: /config
  fileName: config.json
  env:
    enabled: true
    data:
      APP_CONFIG_MODE: configmap
      LOG_LEVEL: info
      FEATURE_VISITS: "true"

persistence:
  enabled: true
  mountPath: /data
  size: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClass: manual
  hostPath:
    enabled: true
    path: /var/local/devops-info-service
  chownOnStart:
    enabled: true
    image:
      repository: busybox
      tag: "1.36"
      pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

secrets:
  enabled: true
  nameOverride: ""
  data:
    username: "change-me"
    password: "change-me"

vault:
  enabled: false
  role: "myapp"
  secretPath: "secret/data/myapp/config"
  injectFilename: "config"
  authPath: "auth/kubernetes"
  agent:
    inject: true
    prePopulateOnly: false
    template:
      enabled: true
      filename: "config.env"
      path: "secret/data/myapp/config"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: false

livenessProbe:
  path: /health
  port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /health
  port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  enabled: true
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  preInstall:
    weight: -5
  postInstall:
    weight: 5
    smokeTestPath: /health
    retries: 15
    sleepSeconds: 2

