replicaCount: 3

image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  nodePort: null

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

hooks:
  postInstall:
    retries: 20
    sleepSeconds: 3
