name: Terraform CI

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    # Переменные окружения для всего job
    env:
      TF_VAR_yc_key_file: ../secrets/yc_key.json # временный путь к ключу
      TF_VAR_ssh_pub_file: ../secrets/yc_ssh.pub # временный SSH ключ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Создаём временный Yandex key из GitHub Secret
      - name: Write YC Key
        run: echo "${{ secrets.YC_KEY_JSON }}" > ../secrets/yc_key.json

      - name: Write SSH public key
        run: echo "${{ secrets.YC_SSH_PUB }}" > ../secrets/yc_ssh.pub

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
        env:
          TF_VAR_yc_key_file: yc_key.json

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        run: tflint --format compact
